title = "爱吃鸡蛋的果果"
baseURL = "https://buxku.com"
# 设置默认的语言 ["en", "zh-cn", "fr", "pl", ...]
defaultContentLanguage = "zh-cn"
# 网站语言，仅在这里 CN 大写 ["en", "zh-CN", "fr", "pl", ...]
languageCode = "zh-CN"
# 是否包括中日韩文字
hasCJKLanguage = true

# 更改使用 Hugo 构建网站时使用的默认主题
theme = "FixIt"

[params]
  # FixIt 主题版本
  version = "0.3.X"
  # 网站描述
  description = "爱吃鸡蛋的果果的小屋"
  # 网站关键词
  keywords = ["果果", "爱吃鸡蛋的果果"]
   # 网站默认主题样式 ["light", "dark", "auto"]
  defaultTheme = "auto"
  # FixIt 0.1.1 | 新增 哪种哈希函数用来 SRI, 为空时表示不使用 SRI
  # ["sha256", "sha384", "sha512", "md5"]
  fingerprint = "md5"
  # FixIt 0.2.0 | 新增 日期格式
  dateFormat = "2006-01-02"
  # 网站图片，用于 Open Graph 和 Twitter Cards
    images = ["/images/avatar.webp"]
  # FixIt 0.2.12 | 新增 开启 PWA 支持
  enablePWA = true
  # FixIt 0.2.14 | 新增 是否自动显示外链图标
  # externalIcon = false
  # FixIt 0.3.0 | 新增 是否反转导航菜单的顺序
  navigationReverse = false
  # FixIt 0.3.0 | 新增 是否在每个页面标题中添加网站标题
  # 请记得在 `hugo.toml` 中设置网站标题 (例如 title = "title")
  withSiteTitle = true
  # FixIt 0.3.0 | 新增 当网站标题被添加到每个页面标题时的标题分隔符
  titleDelimiter = "-"
  # FixIt 0.3.0 | 新增 是否在主页标题中添加网站副标题
  # 请记得通过 `params.header.subtitle.name` 设置网站副标题
  indexWithSubtitle = false
  # FixIt 0.2.14 | 新增 默认情况下，FixIt 只会在主页的 HTML 头中注入主题元标记
  # 你可以将其关闭，但如果你不这样做，我们将不胜感激，因为这是观察 FixIt 受欢迎程度上升的好方法
  disableThemeInject = false

  # 作者配置
  [params.author]
    name = "爱吃鸡蛋的果果"
    email = "313068117@qq.com"
    link = ""
    avatar = "/images/avatar.webp"
  # FixIt 0.3.0 | 新增 公共 Git 仓库信息，仅在 enableGitInfo 设为 true 时有效
  [params.gitInfo]
    # 例如 "https://github.com/hugo-fixit/docs"
    repo = ""
    branch = "main"
    # 相对于仓库根目录的内容目录路径
    dir = "content"
    # 用于报告文章问题的 issue 模板
    # 可用模板参数：{title} {URL} {sourceURL}
    issueTpl = "title=[BUG]%20{title}&body=|Field|Value|%0A|-|-|%0A|Title|{title}|%0A|URL|{URL}|%0A|Filename|{sourceURL}|"
  [params.app]
    # 当添加到 iOS 主屏幕或者 Android 启动器时的标题，覆盖默认标题
    title = "Gg's World!"
    # 是否隐藏网站图标资源链接
     noFavicon = false
    # 更现代的 SVG 网站图标，可替代旧的 .png 和 .ico 文件
    svgFavicon = "/svgFavicon.svg"
    # Safari 图标颜色
    iconColor = "#5bbad5"
    # Windows v8-10 磁贴颜色
    tileColor = "#da532c"
    # FixIt 0.2.12 | 更改 Android 浏览器主题色
    [params.app.themeColor]
      light = "#f8f8f8"
      dark = "#252627"

  # 页面头部导航栏配置
  [params.header]
    # FixIt 0.2.13 | 更改 桌面端导航栏模式 ["sticky", "normal", "auto"]
    desktopMode = "sticky"
    # FixIt 0.2.13 | 更改 移动端导航栏模式 ["sticky", "normal", "auto"]
    mobileMode = "auto"
    # FixIt 0.2.0 | 新增 页面头部导航栏标题配置
    [params.header.title]
      # LOGO 的 URL
      logo = "/images/avatar.webp"
      # 标题名称
      name = "爱吃鸡蛋的果果"
      # 你可以在名称（允许 HTML 格式）之前添加其他信息，例如图标
      pre = "   "
      # 你可以在名称（允许 HTML 格式）之后添加其他信息，例如图标
      post = ""
      # FixIt 0.2.5 | 新增 是否为标题显示打字机动画
      typeit = false
    # FixIt 0.2.12 | 新增 页面头部导航栏副标题配置
    [params.header.subtitle]
      name = "七月の风"
      # 是否为副标题显示打字机动画
      typeit = true

  # FixIt 0.2.18 | 新增 面包屑导航配置
  [params.breadcrumb]
    enable = false
    sticky = false
    showHome = false

  # 页面底部信息配置
  [params.footer]
    enable = true
    # FixIt 0.2.17 | 更改 自定义内容（支持 HTML 格式）
    # 进阶使用，见参数 `params.customFilePath.footer`
    custom = ""
    # FixIt 0.2.0 | 新增 是否显示版权信息
    copyright = true
    # FixIt 0.2.0 | 新增 是否显示作者
    author = true
    # 网站创立年份
    since = 2021
    # FixIt 0.2.12 | 新增 公网安备信息，仅在中国使用（支持 HTML 格式）
    gov = ""
    # FixIt 0.2.12 | 更改 ICP 备案信息，仅在中国使用（支持 HTML 格式）
    icp = "京ICP备2021020928号"
    # 许可协议信息（支持 HTML 格式）
    license = '<a rel="license external nofollow noopener noreferrer" href="https://gg.buxku.com/1705045591799" target="_blank">CC BY-NC-SA 4.0</a>'
    # FixIt 0.3.o | 新增 是否显示 Hugo 和主题信息
    [params.footer.powered]
      enable = false
      hugoLogo = true
      themeLogo = true
      upyunLogo = true
    # FixIt 0.2.17 | 更改 网站创立时间
    [params.footer.siteTime]
      enable = true
      animate = true
      icon = "fa-solid fa-heartbeat"
      pre = ""
      value = "" # e.g. "2021-12-18T16:15:22+08:00"
     # FixIt 0.3.o | 新增 是否显示 upyun 
    [params.footer.upyun]
      enable = true
      hugoLogo = true
      upyunLogo = true
      
    # FixIt 0.2.17 | 新增 页面底部行排序，可选值：["first", 0, 1, 2, 3, 4, 5, "last"]
    [params.footer.order]
      powered = 0
      copyright = 0
      statistics = 0
      visitor = 0
      beian = 0
      upyun = 0

# FixIt 0.2.0 | 新增 Section（所有文章）页面配置
  [params.section]
    # section 页面每页显示文章数量
    paginate = 10
    # 日期格式（月和日）
    dateFormat = "01-02"
    # RSS 文章数目
    rss = 10
    # FixIt 0.2.13 | 新增 最近更新文章设置
    [params.section.recentlyUpdated]
      enable = false
      rss = false
      days = 30
      maxCount = 10

  # FixIt 0.2.0 | 新增 List（目录或标签）页面配置
  [params.list]
    # list 页面每页显示文章数量
    paginate = 10
    # 日期格式（月和日）
    dateFormat = "01-02"
    # RSS 文章数目
    rss = 10

  # FixIt 0.2.17 | 新增 标签云配置
  [params.tagcloud]
    enable = false
    min = 14 # 最小字体大小，单位：px
    max = 32 # 最大字体大小，单位：px
    peakCount = 10 # 每个标签的最大文章数
    orderby = "name" # 标签排序方式，可选值：["name", "count"]

  # 主页配置
  [params.home]
    # FixIt 0.2.0 | 新增 RSS 文章数目
    rss = 10
    # 主页个人信息
    [params.home.profile]
      enable = true
      # Gravatar 邮箱，用于优先在主页显示的头像
      gravatarEmail = "313068117@qq.com"
      # 主页显示头像的 URL
       avatarURL = "/images/avatar.webp"
      # FixIt 0.2.17 | 新增 头像菜单链接的 identifier
       avatarMenu = "https://buxku.com"
      # FixIt 0.2.7 | 更改 主页显示的网站标题（支持 HTML 格式）
      title = "飞流直下三千尺，疑是银河落九天。"
      # 主页显示的网站副标题
      subtitle = "七月の风"
      # 是否为副标题显示打字机动画
      typeit = true
      # 是否显示社交账号
      social = false
      # FixIt 0.2.0 | 新增 免责声明（支持 HTML 格式）
      disclaimer = ""
    # 主页文章列表
    [params.home.posts]
      enable = true
      # 主页每页显示文章数量
      paginate = 6

  # FixIt 0.2.0 | 更改 文章页面配置
  [params.page]
    # FixIt 0.2.18 | 新增 是否启用文章作者头像
    authorAvatar = true
    # FixIt 0.2.0 | 新增 是否在主页隐藏一篇文章
    hiddenFromHomePage = false
    # FixIt 0.2.0 | 新增 是否在搜索结果中隐藏一篇文章
    hiddenFromSearch = false
    # FixIt 0.2.18-lts.5 | 新增 是否在 RSS 中隐藏一篇文章
    hiddenFromRss = false
    # FixIt 0.3.0 | 新增 是否在相关文章中隐藏一篇文章
    hiddenFromRelated = false
    # FixIt 0.2.0 | 新增 是否使用 twemoji
    twemoji = false
    # 是否使用 lightgallery
    # FixIt 0.2.18 | 更改 如果设为 "force"，文章中的图片将强制按照画廊形式呈现
    lightgallery = false
    # FixIt 0.2.0 | 新增 是否使用 ruby 扩展语法
    ruby = true
    # FixIt 0.2.0 | 新增 是否使用 fraction 扩展语法
    fraction = true
    # FixIt 0.2.0 | 新增 是否使用 fontawesome 扩展语法
    fontawesome = true
    # 许可协议信息（支持 HTML 格式）
    license = '<a rel="license external nofollow noopener noreferrer" href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank">CC BY-NC-SA 4.0</a>'
    # 是否显示原始 Markdown 文档内容的链接
    linkToMarkdown = true
    # FixIt 0.3.0 | 新增 是否显示查看文章源码的链接
    linkToSource = true
    # FixIt 0.3.0 | 新增 是否显示编辑文章的链接
    linkToEdit = true
    # FixIt 0.3.0 | 新增 是否显示报告文章问题的链接
    linkToReport = true
    # FixIt 0.2.4 | 新增 是否在 RSS 中显示全文内容
    rssFullText = false
    # FixIt 0.2.13 | 新增 页面样式 ["narrow", "normal", "wide", ...]
    pageStyle = "normal"
    # FixIt 0.2.14 | 新增 FixIt 0.2.18 | 删除 强制使用 Gravatar 作为作者头像
    # gravatarForce = true
    # FixIt 0.2.17 | 更改 开启自动书签支持
    # 如果为 true，则在关闭页面时保存阅读进度
    autoBookmark = false
    # FixIt 0.2.17 | 新增 是否使用 字数统计
    wordCount = true
    # FixIt 0.2.17 | 新增 是否使用 预计阅读
    readingTime = true
    # FixIt 0.2.17 | 新增 文章结束标志
    endFlag = ""
    # FixIt 0.2.18 | 新增 是否开启即时页面
    instantPage = false
    # FixIt 0.3.0 | 新增 是否在侧边栏显示集合列表
    collectionList = false
    # FixIt 0.3.0 | 新增 是否在文章末尾显示集合导航
    collectionNavigation = false

    # FixIt 0.2.15 | 新增 转载配置
    [params.page.repost]
      enable = false
      url = ""
    # FixIt 0.2.0 | 新增 目录配置
    [params.page.toc]
      # 是否使用目录
      enable = true
      # FixIt 0.2.9 | 新增 是否保持使用文章前面的静态目录
      keepStatic = true
      # 是否使侧边目录自动折叠展开
      auto = true
      # FixIt 0.2.13 | 新增 目录位置 ["left", "right"]
      position = "right"
    # FixIt 0.2.13 | 新增 在文章开头显示提示信息，提醒读者文章内容可能过时
    [params.page.expirationReminder]
      enable = false
      # 如果文章最后更新于这天数之前，显示提醒
      reminder = 90
      # 如果文章最后更新于这天数之前，显示警告
      warning = 180
      # 如果文章到期是否关闭评论
      closeComment = false
    # FixIt 0.3.0 | 新增 页面标题配置
    [params.page.heading]
      # 配合 `markup.tableOfContents.ordered` 参数使用
      [params.page.heading.number]
        # 是否启用自动标题编号
        enable = true
        [params.page.heading.number.format]
          h1 = "{title}"
          h2 = "{h2} {title}"
          h3 = "{h2}.{h3} {title}"
          h4 = "{h2}.{h3}.{h4} {title}"
          h5 = "{h2}.{h3}.{h4}.{h5} {title}"
          h6 = "{h2}.{h3}.{h4}.{h5}.{h6} {title}"
    # FixIt 0.2.0 | 新增 代码配置
    [params.page.code]
      # 是否显示代码块的复制按钮
      copy = true
      # FixIt 0.2.13 | 新增 是否显示代码块的编辑按钮
      edit = true
      # 默认展开显示的代码行数
      maxShownLines = 10
    # FixIt 0.2.0 | 更改 KaTeX 数学公式 (https://katex.org)
  [params.page.math]
      enable = true
      # 默认行内定界符是 $ ... $ 和 \( ... \)
      inlineLeftDelimiter = ""
      inlineRightDelimiter = ""
      # 默认块定界符是 $$ ... $$, \[ ... \],  \begin{equation} ... \end{equation} 和一些其它的函数
      blockLeftDelimiter = ""
      blockRightDelimiter = ""
      # KaTeX 插件 copy_tex
      copyTex = true
      # KaTeX 插件 mhchem
      mhchem = true
  # FixIt 0.2.0 | 新增 Mapbox GL JS 配置 (https://docs.mapbox.com/mapbox-gl-js)
    [params.page.mapbox]
      # Mapbox GL JS 的 access token
      accessToken = ""
      # 浅色主题的地图样式
      lightStyle = "mapbox://styles/mapbox/light-v9"
      # 深色主题的地图样式
      darkStyle = "mapbox://styles/mapbox/dark-v9"
      # 是否添加 NavigationControl
      navigation = true
      # 是否添加 GeolocateControl
      geolocate = true
      # 是否添加 ScaleControl
      scale = true
      # 是否添加 FullscreenControl
      fullscreen = true
  # FixIt 0.3.0 | 新增 [试验性功能] 缓存图床图片到本地，详见：https://github.com/hugo-fixit/FixIt/pull/362
    [params.page.cacheRemoteImages]
      enable = false
      # 用本地图片链接替换远程图片链接 (放置在 public/images/remote/)
      replace = false
    # FixIt 0.3.0 | 新增 相关内容配置 (https://gohugo.io/content-management/related/)
    [params.page.related]
      enable = false
      count = 5
  # FixIt 0.2.17 | 新增 赞赏设置
    [params.page.reward]
      enable = true
      animation = false
      # 相对于页脚的位置，可选值：["before", "after"]
      position = "after"
      # comment = "Buy me a coffee"
      # FixIt 0.2.18 | 新增 二维码图片展示模式，可选值：["static", "fixed"]，默认：`static`
      mode = "static"
      [params.page.reward.ways]
        # wechatpay = "/images/wechatpay.png"
        # alipay = "/images/alipay.png"
        # paypal = "/images/paypal.png"
        # bitcoin = "/images/bitcoin.png"
# FixIt 0.2.0 | 更改 文章页面的分享信息设置
    [params.page.share]
      enable = true
      Twitter = true
      Facebook = true
      Linkedin = false
      Whatsapp = true
      Pinterest = false
      Tumblr = false
      HackerNews = false
      Reddit = false
      VK = false
      Buffer = false
      Xing = false
      Line = true
      Instapaper = false
      Pocket = false
      Flipboard = false
      Weibo = true
      Myspace = true
      Blogger = true
      Baidu = false
      Odnoklassniki = false
      Evernote = true
      Skype = false
      Trello = false
      Mix = false

# FixIt 0.2.7 | 新增 第三方库配置
    [params.page.library]
      [params.page.library.css]
        # someCSS = "some.css"
        # 位于 "assets/"
        # 或者
        # someCSS = "https://cdn.example.com/some.css"
      [params.page.library.js]
        # someJavascript = "some.js"
        # 位于 "assets/"
        # 或者
        # someJavascript = "https://cdn.example.com/some.js"
    # FixIt 0.2.10 | 更改 页面 SEO 配置
    [params.page.seo]
      # 图片 URL
      images = []
      # 出版者信息
      [params.page.seo.publisher]
        name = "爱吃鸡蛋的果果"
        logoUrl = ""

# FixIt 0.2.10 | 新增 网站 SEO 配置
  [params.seo]
    # 图片 URL
    image = ""
    # 缩略图 URL
    thumbnailUrl = ""

  # FixIt 0.2.0 | 新增 网站分析配置
  [params.analytics]
    enable = false
    # Google Analytics
    [params.analytics.google]
      id = ""
      # 是否匿名化用户 IP
      anonymizeIP = true
    # Fathom Analytics
    [params.analytics.fathom]
      id = ""
      # 自行托管追踪器时的主机路径
      server = ""

  # FixIt 0.2.7 | 新增 Cookie 许可配置
  [params.cookieconsent]
    enable = true
    # 用于 Cookie 许可横幅的文本字符串
    [params.cookieconsent.content]
      message = ""
      dismiss = ""
      link = ""
# FixIt 0.2.7 | 更改 第三方库文件的 CDN 设置
  [params.cdn]
    # CDN 数据文件名称，默认不启用 ["jsdelivr.yml", "unpkg.yml", ...]
    # 位于 "themes/FixIt/assets/data/cdn/" 目录
    # 可以在你的项目下相同路径存放你自己的数据文件："assets/data/cdn/"
    # data = "unpkg.yml"

  # FixIt 0.2.8 | 新增 兼容性设置
  [params.compatibility]
    # 是否使用 Polyfill.io 来兼容旧式浏览器
    polyfill = false
    # 是否使用 object-fit-images 来兼容旧式浏览器
    objectFit = false
 # FixIt 0.2.14 | 新增 Gravatar 设置
  [params.gravatar]
    # FixIt 0.2.18 | 新增 取决于作者邮箱，作者邮箱未设置则使用本地头像
    enable = false
    # Gravatar 主机，默认：“www.gravatar.com”
    host = "www.buxku.com" # ["cn.gravatar.com", "gravatar.loli.net", ...]
    style = "" # ["", "mp", "identicon", "monsterid", "wavatar", "retro", "blank", "robohash"]


# FixIt 0.2.5 | 新增 TypeIt 配置
  [params.typeit]
    # 每一步的打字速度（单位是毫秒）
    speed = 100
    # 光标的闪烁速度（单位是毫秒）
    cursorSpeed = 1000
    # 光标的字符（支持 HTML 格式）
    cursorChar = "|"
    # 打字结束之后光标的持续时间（单位是毫秒，"-1" 代表无限大）
    duration = -1
    # FixIt 0.2.18 | 新增 打字完成后是否会连续循环
    loop = false

  # FixIt 0.2.15 | 新增 Mermaid 配置
  [params.mermaid]
    # 取值详见 https://mermaid.js.org/config/theming.html#available-themes
    themes = ["default", "dark"]

  # FixIt 0.2.12 | 新增 盘古之白配置
  [params.pangu]
    # 适用于中文写作用户
    enable = false
    selector = "article" # FixIt 0.2.17 | 新增

# FixIt 0.2.12 | 新增 水印配置
  # 详细参数见 https://github.com/Lruihao/watermark#readme
  [params.watermark]
    enable = false
    # 水印内容（允许 HTML 格式）
    content = ""
    # 水印透明度
    opacity = 0.1
    # 单水印宽度 单位：px
    width = 150
    # 单水印高度 单位：px
    height = 20
    # 水印行间距 单位：px
    rowSpacing = 60
    # 水印列间距 单位：px
    colSpacing = 30
    # 水印旋转角度 单位：deg
    rotate = 15
    # 水印字体大小，单位：rem
    fontSize = 0.85
    # FixIt 0.2.13 | 新增 水印字体
    fontFamily = "inherit"

# FixIt 0.2.12 | 新增 不蒜子统计
  [params.ibruce]
    enable = false
    # 在文章中开启
    enablePost = false

# 网站验证代码，用于 Google/Bing/Yandex/Pinterest/Baidu/360/Sogou
  [params.verification]
    google = ""
    bing = ""
    yandex = ""
    pinterest = ""
    baidu = ""
    so = ""
    sogou = ""

# FixIt 0.2.16 | 新增 返回顶部
  [params.backToTop]
    enable = true
    # 在 b2t 按钮中显示滚动百分比
    scrollpercent = false

  # FixIt 0.2.16 | 新增 阅读进度条
  [params.readingProgress]
    enable = true
    # 可用值：["left", "right"]
    start = "left"
    # 可用值：["top", "bottom"]
    position = "top"
    reversed = false
    light = ""
    dark = ""
    height = "2px"

  # FixIt 0.2.17 | 新增 页面加载期间顶部的进度条
  # 有关详细信息：https://github.com/CodeByZach/pace
  [params.pace]
    enable = true
    # 所有可用颜色：
    # ["black", "blue", "green", "orange", "pink", "purple", "red", "silver", "white", "yellow"]
    color = "blue"
    # 所有可用主题：
    # ["barber-shop", "big-counter", "bounce", "center-atom", "center-circle", "center-radar", "center-simple",
    # "corner-indicator", "fill-left", "flash", "flat-top", "loading-bar", "mac-osx", "material", "minimal"]
    theme = "minimal"

# FixIt 0.2.17 | 新增 定义自定义文件路径
  # 在站点目录 `layouts/partials/custom` 中创建你的自定义文件，并取消注释下面需要的文件
  [params.customFilePath]
    # aside = "custom/aside.html"
    # profile = "custom/profile.html"
    # footer = "custom/footer.html"


# 网站地图配置
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# Permalinks 配置 (https://gohugo.io/content-management/urls#permalinks)
[Permalinks]
  # posts = ":year/:month/:filename"
  #posts = ":filename"
  [Permalinks.page]
    posts = "/posts/:slug/"
  

# 隐私信息配置 (https://gohugo.io/about/hugo-and-gdpr/)
[privacy]
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true

# FixIt 0.2.15 | 更改
[mediaTypes]
  # 用于输出 Markdown 格式文档的设置
  [mediaTypes."text/markdown"]
    suffixes = ["md"]
  # 用于输出 txt 格式文档的设置
  [mediaTypes."text/plain"]
    suffixes = ["txt"]

[outputFormats]
  # 用于输出 Markdown 格式文档的设置
  [outputFormats.MarkDown]
    mediaType = "text/markdown"
    isPlainText = true
    isHTML = false
  # FixIt 0.3.0 | 新增 用于输出 /archives/index.html 文件的设置
  [outputFormats.archives]
    path = "archives"
    baseName = "index"
    mediaType = "text/html"
    isPlainText = false
    isHTML = true
    permalinkable = true
  # FixIt 0.3.0 | 新增 用于输出 /offline/index.html 文件的设置
  [outputFormats.offline]
    path = "offline"
    baseName = "index"
    mediaType = "text/html"
    isPlainText = false
    isHTML = true
    permalinkable = true
  # FixIt 0.3.0 | 新增 用于输出 readme.md 文件的设置
  [outputFormats.README]
    baseName = "readme"
    mediaType = "text/markdown"
    isPlainText = true
    isHTML = false
  # FixIt 0.3.0 | 更改 用于输出 baidu_urls.txt 文件的设置
  [outputFormats.baidu_urls]
    baseName = "baidu_urls"
    mediaType = "text/plain"
    isPlainText = true
    isHTML = false

# 用于 Hugo 输出文档的设置，可选值如下：
# home: ["HTML", "RSS", "JSON", "archives", "offline", "README", "baidu_urls"]
# page: ["HTML", "MarkDown"]
# section: ["HTML", "RSS"]
# taxonomy: ["HTML", "RSS"]
# term: ["HTML", "RSS"]
[outputs]
  home = ["HTML", "RSS", "JSON", "archives", "offline"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML"]
  term = ["HTML", "RSS"]





[menu]
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    identifier = "categories"
    name = "分类"
    url = "/categories/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 3
    [[menu.main]]
    identifier = "moment"
    name = "说说"
    url = "/moment/"
    weight = 4  
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 5



# Hugo 解析文档的配置
[markup]
  # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    ################## 必要的配置 ##################
    # https://github.com/hugo-fixit/FixIt/issues/43
    codeFences = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    ################## 必要的配置 ##################
    guessSyntax = true
  # Goldmark 是 Hugo 0.60 以来的默认 Markdown 解析库
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # 是否在文档中直接使用 HTML 标签
      unsafe = true
  # 目录设置
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6
